/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MoreInfomation.java
 *
 * Created on May 10, 2013, 9:01:05 PM
 */
package bonafide;

import java.sql.SQLException;


/**
 *
 * @author ishant0
 */
public class MoreInfomation extends javax.swing.JFrame {

    /** Creates new form MoreInfomation */
    public MoreInfomation() {
        initComponents();
        enterChoicetf.setVisible(false);
        table.setVisible(false);
        try
        {
            Class.forName("org.sqlite.JDBC");
            con = java.sql.DriverManager.getConnection("jdbc:sqlite:C:/Documents and Settings/ishant0/bonafide.db");
        }
         catch(Exception e){
             javax.swing.JOptionPane.showMessageDialog(null, "Problem in connecting with data");             
         }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        byCombo = new javax.swing.JComboBox();
        enterChoicel = new javax.swing.JLabel();
        enterChoicetf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Want to see information by:");

        byCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "rollnum", "name", "date", "course", "sem", " ", " " }));
        byCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                byComboActionPerformed(evt);
            }
        });

        enterChoicetf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterChoicetfActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Rollnumber", "name", "course", "semester", "date"
            }
        ));
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enterChoicel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(byCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enterChoicetf, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(byCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(enterChoicel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(enterChoicetf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void byComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byComboActionPerformed
    String selected = (String)byCombo.getSelectedItem();
    enterChoicel.setText("Enter " + selected);
    enterChoicetf.setVisible(true);
}//GEN-LAST:event_byComboActionPerformed

private void enterChoicetfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterChoicetfActionPerformed
    table.setVisible(true);
    //table.setValueAt("Shifali", 1, 1);
    getData();
}//GEN-LAST:event_enterChoicetfActionPerformed

    /**
     * @param args the command line arguments
     */

     private void getData(){
         try{
         ps = con.prepareStatement("select * from firstInfo where ? = ?"); 
         ps.setString(1, (String)byCombo.getSelectedItem());
         ps.setString(2, enterChoicetf.getText());
         rs = ps.executeQuery();
         System.out.println(byCombo.getSelectedItem());
         System.out.println(enterChoicetf.getText());
         int i = 0;
         if(rs.next()){
             do{
                 table.setValueAt(rs.getString("rollnum"), i, i); 
                 table.setValueAt(rs.getString("name"), i, i);
                 table.setValueAt(rs.getString("course"), i, i);
                 table.setValueAt(rs.getString("sem"), i, i);
                 table.setValueAt(rs.getString("date"), i, i);
                 i++;
             }while(rs.next());
         }
         else{
             javax.swing.JOptionPane.showMessageDialog(null, "No certificate issued with " + enterChoicetf.getText());
         }
         con.close();
         }
         catch(java.sql.SQLException e){
             javax.swing.JOptionPane.showMessageDialog(null, "Problem in fetching data");
             e.printStackTrace();
         }
     }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoreInfomation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoreInfomation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoreInfomation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoreInfomation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MoreInfomation().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox byCombo;
    private javax.swing.JLabel enterChoicel;
    private javax.swing.JTextField enterChoicetf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
    private java.sql.Connection con;
    private java.sql.PreparedStatement ps;
    private java.sql.Statement st;
    private java.sql.ResultSet rs;
}
